
modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL3 / CC BY-NC-ND 4.0"

[[mods]] #mandatory
modId="packapunch" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Pack A Punched" #mandatory
logoFile="packapunch.png" #optional
credits="" #optional
authors="tropidragon" #optional

description='''
A mod that mega upgrade your guns from TAC:Z!
'''
[[dependencies.packapunch]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.packapunch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"